# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Picture', models.CharField(max_length=120)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Abilities', models.CharField(max_length=40)),
                ('Deff', models.IntegerField()),
                ('Attack', models.IntegerField()),
                ('Speed', models.IntegerField()),
                ('Appearence', models.CharField(max_length=120)),
                ('skill_type', models.CharField(choices=[('0', 'Fire'), ('1', 'Water'), ('2', 'Poison'), ('3', 'Grass'), ('4', 'Bug'), ('5', 'Electric'), ('6', 'Ice'), ('7', 'Fairy'), ('8', 'Ground'), ('9', 'Dark'), ('10', 'Psychic'), ('11', 'Fighting'), ('12', 'Steel'), ('13', 'Ghost'), ('14', 'Dragon'), ('15', 'Flying')], max_length=1)),
                ('gender_type', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1)),
                ('generation_type', models.CharField(choices=[('0', 'I'), ('1', 'II'), ('2', 'III'), ('3', 'IV'), ('4', 'V'), ('5', 'VI'), ('6', 'VII')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Picture', models.CharField(max_length=120)),
                ('Appearance', models.CharField(max_length=120)),
                ('gender_type', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1)),
                ('region_type', models.CharField(choices=[('0', 'Kanto'), ('1', 'Johto'), ('2', 'Hoenn'), ('3', 'Sinnoh'), ('4', 'Unova'), ('5', 'Kalos'), ('6', 'Alola')], max_length=1)),
            ],
        ),
    ]
