# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0004_auto_20171209_1632'),
        ('poke', '0005_auto_20171209_1639'),
    ]

    operations = [
    ]
