# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0012_auto_20171210_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Pokemons',
            field=models.ManyToManyField(to='poke.Pokemon'),
        ),
    ]
