# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0013_auto_20171210_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='Pokemons',
        ),
    ]
