# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0014_remove_trainer_pokemons'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Pokemons',
            field=models.ManyToManyField(to='poke.Pokemon'),
        ),
    ]
