# Generated by Django 2.0 on 2017-12-12 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0018_auto_20171210_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='CompareTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 14, 1, 59, 484260)),
        ),
        migrations.AlterField(
            model_name='compare',
            name='First',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='Second',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Second', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender_type',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', '%50 Male %50 Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Pokemons',
            field=models.ManyToManyField(to='poke.Pokemon'),
        ),
    ]
