# Generated by Django 2.0 on 2017-12-12 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0019_auto_20171212_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='HP',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='compare',
            name='CompareTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 21, 39, 12, 719105)),
        ),
        migrations.AlterField(
            model_name='compare',
            name='First',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='Second',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Second', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='Height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='Weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Pokemons',
            field=models.ManyToManyField(to='poke.Pokemon'),
        ),
    ]
