# Generated by Django 2.0 on 2017-12-24 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0020_auto_20171212_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='CompareTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 16, 8, 58, 135146)),
        ),
        migrations.AlterField(
            model_name='compare',
            name='First',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='Second',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Second', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Pokemons',
            field=models.ManyToManyField(to='poke.Pokemon'),
        ),
    ]
