# Generated by Django 2.0 on 2017-12-28 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0021_auto_20171224_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='CompareTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 14, 28, 1, 573655)),
        ),
        migrations.AlterField(
            model_name='compare',
            name='First',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='compare',
            name='Second',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Second', to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Appearance',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Pokemons',
            field=models.ManyToManyField(to='poke.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender_type',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='region_type',
            field=models.CharField(choices=[('0', 'Kanto'), ('1', 'Johto'), ('2', 'Hoenn'), ('3', 'Sinnoh'), ('4', 'Unova'), ('5', 'Kalos'), ('6', 'Alola')], default=6, max_length=1),
        ),
    ]
